url: http://dawnmercurio.github.io
baseurl: 

# Site settings
title: Dawn Mercurio
email: dawnmercurio@domain.com
description: "Dawn Mercurio is a Designer in the Mid-Atlantic era specializing in educational and higher ed design. After a ten-year immersion in print design, she returned to web design to find that everything is dynamic. Jekyll looked unique, refreshing and offered lots of tutorials and beautiful templates like this one."


# Color settings (hex-codes without the leading hash-tag) fed136 fec503
color:
  primary: ebc8b7
  secondary: ebc8b7  
  secondary-dark: 333


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/DawnMercurioDesignAndIllustration
  - title: behance 
    url: https://www.behance.net/dawnmercurio
  - title: linkedin
    url: https://www.linkedin.com/in/dawnmmercurio

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty